import {
  type AccessorFn,
  type AggregationFn,
  type Cell,
  type Column,
  type ColumnDef,
  type ColumnFiltersState,
  type ColumnOrderState,
  type ColumnPinningState,
  type ColumnSizingInfoState,
  type ColumnSizingState,
  type DeepKeys,
  type DeepValue,
  type ExpandedState,
  type FilterFn,
  type GroupingState,
  type Header,
  type HeaderGroup,
  type OnChangeFn,
  type PaginationState,
  type Row,
  type RowSelectionState,
  type SortingFn,
  type SortingState,
  type Table,
  type TableOptions,
  type TableState,
  type Updater,
  type VisibilityState,
} from "@tanstack/vue-table"
import {
  type VirtualItem,
  type Virtualizer,
  type VirtualizerOptions,
} from "@tanstack/vue-virtual"

export enum Size {
  dot = "dot",
  xs = "xs",
  sm = "sm",
  md = "base",
  base = "base",
  lg = "lg",
  xl = "xl",
  "2xl" = "2xl",
  "3xl" = "3xl",
  "4xl" = "4xl",
  "5xl" = "5xl",
  "6xl" = "6xl",
  "7xl" = "7xl",
  "8xl" = "8xl",
  "9xl" = "9xl",
}

export enum BaseColor {
  warning = "warning",
  error = "error",
  info = "info",
  success = "success",
  primary = "primary",
  brand = "brand",
  default = "default",
}
